import type { ReactNode } from 'react';

import { REVIEWER_MODEL } from '@/agent/lib/review/summary';

import { DECISIONS, type Decision, type SummaryStatus } from './display';
import { plainReason } from './errors';
import { PendingDot } from './PendingDot';

/**
 * One component for the whole-change and per-file reviews, so they read as
 * one voice. The status is exposed on `data-summary`.
 */
export function ReviewNote({
  status,
  text,
  decision,
  error,
  footnote,
  model,
  pills,
  incomplete = false,
  writing = false,
  tone = 'file',
}: {
  status: SummaryStatus;
  text: string | null | undefined;
  /** Only the whole-change review has one. */
  decision?: Decision | null;
  footnote?: ReactNode;
  pills?: ReactNode;
  error?: string | null;
  model?: string | null;
  /** Luna hit its length limit in this block. */
  incomplete?: boolean;
  /** Shows the streaming caret. */
  writing?: boolean;
  tone?: 'overall' | 'file';
}) {
  const badge = decision ? DECISIONS[decision] : null;

  return (
    <section
      className={`rounded-md border border-line ${tone === 'overall' ? 'bg-surface' : 'bg-page'} px-3 py-2`}
      data-summary={status}
    >
      {status === 'stale' && (
        <div className="mb-1 flex">
          <span className="ml-auto flex shrink-0 items-center gap-1.5 text-xs text-muted">
            <PendingDot tone="bg-warn" />
            reviewing…
          </span>
        </div>
      )}
      <Body
        error={error}
        incomplete={incomplete}
        status={status}
        text={text}
        tone={tone}
        writing={writing}
      />
      <div className="mt-1.5 flex flex-wrap items-center gap-x-2 gap-y-1">
        {badge ? (
          <span
            className={`rounded-full px-2 py-0.5 text-xs font-semibold ${badge.className}`}
            data-decision={decision}
          >
            {badge.label}
          </span>
        ) : null}
        {pills}
        {/* Own line on phones: four pills and this do not fit one line. */}
        <p
          className="w-full text-xs text-subtle lg:ml-auto lg:w-auto lg:text-right"
          data-generated-by={true}
        >
          Generated by {model?.trim() || REVIEWER_MODEL}
        </p>
      </div>
      {footnote}
    </section>
  );
}

/** Fits one line. */
const ERROR_CHARS = 120;

function Body({
  status,
  text,
  error,
  incomplete,
  tone,
  writing,
}: {
  status: SummaryStatus;
  text: string | null | undefined;
  error?: string | null;
  incomplete: boolean;
  tone: 'overall' | 'file';
  writing: boolean;
}) {
  if (status === 'pending' || (!text && status !== 'failed')) {
    return (
      <p className="flex items-center gap-2 text-base text-muted lg:text-sm">
        <span aria-hidden="true" className="spinner" />
        Luna is reviewing…
      </p>
    );
  }
  if (!text && incomplete) {
    return (
      <p className="text-base text-muted lg:text-sm" data-incomplete="true">
        No review: Luna ran into its length limit before it reached this.
      </p>
    );
  }
  if (!text) {
    const why = error ? plainReason(error.trim()).slice(0, ERROR_CHARS) : '';

    return (
      <p className="text-base text-muted lg:text-sm">
        {why ? `No review: ${why}` : 'No review yet'}
      </p>
    );
  }

  return (
    <>
      <p
        className={`leading-relaxed text-ink ${tone === 'overall' ? 'text-base lg:text-sm' : 'text-sm lg:text-sm'}`}
        style={status === 'stale' ? { opacity: 0.5 } : undefined}
      >
        {ticked(text)}
        {writing ? <span aria-hidden="true" className="caret" /> : null}
      </p>
      {incomplete && !writing ? (
        <p className="mt-1 text-xs text-muted" data-incomplete="true">
          Cut off: Luna ran into its length limit, so this is as far as it got.
        </p>
      ) : null}
    </>
  );
}

/**
 * The only markdown the page reads. Rendered as React nodes, so nothing the
 * model writes can become markup.
 */
function ticked(text: string): ReactNode[] {
  return text.split(/(`[^`\n]+`)/g).map((part, i) =>
    part.length > 2 && part.startsWith('`') && part.endsWith('`') ? (
      <code
        className="rounded bg-track px-1 py-px font-mono text-xs text-ink"
        // Index alone would keep a stale node while the text streams in.
        key={`${i}:${part}`}
      >
        {part.slice(1, -1)}
      </code>
    ) : (
      part
    ),
  );
}
