/**
 * What the reviewer subagent (Luna) writes, and how it is read back.
 *
 * The reviewer writes plain text in a fixed layout rather than structured
 * output, so that the page can stream it in as it is generated:
 *
 *   Decision: request_changes
 *   ## Overall
 *   <three to five sentences>
 *   ## src/path/one.ts
 *   <two to three sentences>
 *   ## src/path/two.ts
 *   …
 *
 * `parseSummaryText` is tolerant of partial text, so it can run on every
 * streamed delta as well as on the final result.
 *
 * Some lines are the adapter's, never the model's, and are read as signals
 * rather than as text: `OVERALL_REWRITE_LINE` before the overall part is
 * written again, and `cutOffLine` after a part that was cut off even so. A
 * file part is written after reading someone else's code, so its text is
 * untrusted: `withoutSignalLines` drops every line of model text shaped like
 * a signal before the parser can see it, and the parser takes the decision,
 * the overall paragraph and a rewrite only from the part that comes first,
 * the overall one, before any file section has opened.
 */

/**
 * Written before the overall part is written again, having run into its
 * output ceiling: what it wrote before is dropped. A file part written again
 * needs no line of its own, because a repeated file section replaces the one
 * before it.
 */
export const OVERALL_REWRITE_LINE = '<!-- overall written again -->';

/** How the overall section is named in a `cutOffLine`. */
export const OVERALL_SECTION = 'overall';

const CUT_OFF = /^<!-- cut off: (.+) -->$/;

/** What every signal line starts with, once trimmed. */
const SIGNAL_START = '<!--';

/**
 * Model text as it streams, with every line that begins with an HTML comment
 * dropped, so that only the adapter can write a signal line. A line is held
 * back only while it could still become one; anything else streams at once.
 * `\r` ends a line too, because the parser reads it as one.
 */
export function withoutSignalLines(push: (delta: string) => void): {
  write(delta: string): void;
  end(): void;
} {
  /** The start of the current line, held while it may yet be a signal. */
  let held = '';
  /** The current line is known not to be one, and streams as it comes. */
  let plain = false;
  const settleHeld = () => {
    const head = held.trimStart();
    if (
      head.length > 0 &&
      !SIGNAL_START.startsWith(head) &&
      !head.startsWith(SIGNAL_START)
    ) {
      push(held);
      held = '';
      plain = true;
    }
  };
  const endLine = () => {
    // A held line that got this far is a comment line, or blank.
    if (!held.trimStart().startsWith(SIGNAL_START)) {
      push(held);
    }
    held = '';
    plain = false;
  };
  return {
    end: endLine,
    write(delta) {
      for (const piece of delta.split(/(\r\n|\r|\n)/)) {
        if (piece === '\n' || piece === '\r' || piece === '\r\n') {
          endLine();
          push(piece);
        } else if (plain) {
          push(piece);
        } else if (piece) {
          held += piece;
          settleHeld();
        }
      }
    },
  };
}

/**
 * Written after a part that was cut off at its ceiling twice, once for each
 * section it leaves incomplete: the one it stopped in, and any it never
 * reached. `section` is a path, or `OVERALL_SECTION`.
 */
export function cutOffLine(section: string): string {
  return `<!-- cut off: ${section} -->`;
}

/** Files per reviewer task. A review is split into parallel tasks of this many files, plus one overall task. */
export const REVIEW_BATCH_SIZE = 6;

/** What one reviewer task was asked for. */
type ReviewPartRole = 'files' | 'overall';

export interface ReviewPart {
  role: ReviewPartRole;
  /** Batch index for "files" parts; 0 for the overall part. */
  index: number;
  /** The paths this part covers (every path for the overall part). */
  paths: string[];
}

/** The model behind the reviewer, shown as "Generated by …". */
export const REVIEWER_MODEL = 'openai/gpt-5.6-luna-fast';

type Decision = 'approve' | 'comment' | 'request_changes';

export interface Summary {
  overall: string;
  decision: Decision;
  files: { path: string; summary: string; incomplete?: true }[];
  /** The overall part was cut off at its output ceiling twice: what is here is all it wrote. */
  overallIncomplete?: true;
  /** True when the text is still arriving and the last section may be cut. */
  partial?: boolean;
  /**
   * The section the text ended in, still open: a path, `OVERALL_SECTION`, or
   * null. While a review streams it is the one being written, which is not
   * always the last in `files`: a part written again repeats sections that
   * keep their first place.
   */
  writing: string | null;
}

const DECISIONS: readonly Decision[] = [
  'approve',
  'comment',
  'request_changes',
];

/** The review as it is being read, line by line. */
interface SummaryParse {
  /** The section being read into, which is `overall` while that is the one. */
  current: string[] | null;
  /** The path that section is about, or null while the overall one is open. */
  currentPath: string | null;
  decision: Decision;
  files: { path: string; summary: string; incomplete?: true }[];
  /** Paths cut off by their part's output ceiling. */
  incomplete: Set<string>;
  overall: string[];
  overallIncomplete: boolean;
  /**
   * A file section has opened: the overall part is over, and nothing after
   * this may set the decision, add to the overall paragraph or restart it.
   */
  filesStarted: boolean;
}

/**
 * A `Decision:` line: the decision it names, 'unrecognised' when the line is
 * one but the word is not a decision, and null when it is not one at all.
 */
function readDecisionLine(line: string): Decision | 'unrecognised' | null {
  const match = /^\s*\**decision\**\s*[:：]\s*\**\s*([a-z_ ]+)/i.exec(line);
  if (!match) {
    return null;
  }
  const named = match[1].trim().toLowerCase().replace(/\s+/g, '_') as Decision;
  return DECISIONS.includes(named) ? named : 'unrecognised';
}

/** A heading's title, stripped of the decoration models put around paths. */
function readHeading(line: string): string | null {
  const heading = /^\s*#{1,6}\s+(.+?)\s*$/.exec(line);
  // Models decorate headings: `path`, **path**, _path_.
  return heading ? heading[1].replace(/^[`*_\s]+|[`*_\s]+$/g, '').trim() : null;
}

/**
 * Close the section being read, if one is open. A path written twice keeps
 * its first place and its last text: a part written again repeats sections.
 */
function flushSection(parse: SummaryParse): void {
  if (parse.currentPath !== null && parse.current) {
    const section = {
      path: parse.currentPath,
      summary: parse.current.join('\n').trim(),
    };
    const earlier = parse.files.findIndex((f) => f.path === section.path);
    if (earlier === -1) {
      parse.files.push(section);
    } else {
      parse.files[earlier] = section;
    }
  }
  parse.current = null;
  parse.currentPath = null;
}

/** One of the adapter's own lines: true when `line` was one and has been acted on. */
function readSignalLine(parse: SummaryParse, line: string): boolean {
  const trimmed = line.trim();
  if (trimmed === OVERALL_REWRITE_LINE) {
    // Only the overall part is ever written again this way, and it comes first.
    if (parse.filesStarted) {
      return true;
    }
    flushSection(parse);
    // The overall part starts over, its decision line included.
    parse.overall.length = 0;
    parse.overallIncomplete = false;
    parse.current = parse.overall;
    return true;
  }
  const cut = CUT_OFF.exec(trimmed)?.[1];
  if (cut === undefined) {
    return false;
  }
  if (cut === OVERALL_SECTION) {
    parse.overallIncomplete = true;
  } else {
    parse.incomplete.add(cut);
  }
  return true;
}

/**
 * Open the section a heading names. A second `Overall` continues the first,
 * unless a file section has opened since: an `Overall` in a file part's text
 * is read into nothing.
 */
function openSection(parse: SummaryParse, title: string): void {
  flushSection(parse);
  if (/^overall$/i.test(title)) {
    parse.currentPath = null;
    parse.current = parse.filesStarted ? [] : parse.overall;
    return;
  }
  parse.filesStarted = true;
  parse.currentPath = title;
  parse.current = [];
}

/** Read one line of the reviewer's text into the parse. */
function readSummaryLine(parse: SummaryParse, raw: string): void {
  const line = raw.trimEnd();
  if (readSignalLine(parse, line)) {
    return;
  }
  const named = readDecisionLine(line);
  if (
    named &&
    !parse.filesStarted &&
    parse.currentPath === null &&
    parse.overall.length === 0
  ) {
    if (named !== 'unrecognised') {
      parse.decision = named;
    }
    return;
  }
  // A bare "##" is a heading still arriving: hold it out of the text.
  if (/^\s*#{1,6}\s*$/.test(line)) {
    return;
  }
  const title = readHeading(line);
  if (title !== null) {
    openSection(parse, title);
    return;
  }
  parse.current?.push(line);
}

export function parseSummaryText(text: string, partial = false): Summary {
  const parse: SummaryParse = {
    current: null,
    currentPath: null,
    decision: 'comment',
    files: [],
    filesStarted: false,
    incomplete: new Set(),
    overall: [],
    overallIncomplete: false,
  };
  for (const raw of text.replace(/\r\n?/g, '\n').split('\n')) {
    readSummaryLine(parse, raw);
  }
  const writing =
    parse.currentPath ??
    (parse.current === parse.overall ? OVERALL_SECTION : null);
  flushSection(parse);
  return {
    decision: parse.decision,
    files: [
      ...parse.files.map((f) =>
        parse.incomplete.has(f.path) ? { ...f, incomplete: true as const } : f,
      ),
      // A section a cut-off part never reached is still one to say is missing.
      ...[...parse.incomplete]
        .filter((path) => !parse.files.some((f) => f.path === path))
        .map((path) => ({ incomplete: true as const, path, summary: '' })),
    ],
    overall: parse.overall.join('\n').trim(),
    ...(parse.overallIncomplete ? { overallIncomplete: true as const } : {}),
    ...(partial ? { partial: true } : {}),
    writing,
  };
}
