/**
 * What the reviewer subagent (Luna) writes, and how it is read back.
 *
 * The reviewer writes plain text in a fixed layout rather than structured
 * output, so that the page can stream it in as it is generated:
 *
 *   Decision: request_changes
 *   ## Overall
 *   <three to five sentences>
 *   ## src/path/one.ts
 *   <two to three sentences>
 *   ## src/path/two.ts
 *   …
 *
 * `parseSummaryText` is tolerant of partial text, so it can run on every
 * streamed delta as well as on the final result.
 */

/**
 * The per-file length the reviewer is asked for, in characters. This is a
 * promise the model keeps through its instructions; the parser never cuts
 * text, so a longer section is visible as such rather than silently trimmed.
 */
export const FILE_SUMMARY_MAX_CHARS = 300;

/** Files per reviewer task. A review is split into parallel tasks of this many files, plus one overall task. */
export const REVIEW_BATCH_SIZE = 6;

/** What one reviewer task was asked for. */
export type ReviewPartRole = "files" | "overall";

export interface ReviewPart {
  role: ReviewPartRole;
  /** Batch index for "files" parts; 0 for the overall part. */
  index: number;
  /** The paths this part covers (every path for the overall part). */
  paths: string[];
}

/**
 * Combine the parts of a batched review. Sections are ordered by the parts'
 * batch order, and the decision and overall text come from whichever part
 * carried them (the overall task). Works on partial input too.
 */
export function mergeSummaryParts(parts: { part: ReviewPart; summary: Summary }[]): Summary {
  const overall = parts.find((p) => p.part.role === "overall" && p.summary.overall);
  const files = parts
    .filter((p) => p.part.role === "files")
    .sort((a, b) => a.part.index - b.part.index)
    .flatMap((p) => p.summary.files);
  const partial = parts.some((p) => p.summary.partial);
  return {
    overall: overall?.summary.overall ?? "",
    decision: overall?.summary.decision ?? "comment",
    files,
    ...(partial ? { partial: true } : {}),
  };
}

/** The model behind the reviewer, shown as "Generated by …". */
export const REVIEWER_MODEL = "openai/gpt-5.6-luna-fast";

export type Decision = "approve" | "comment" | "request_changes";

export interface Summary {
  overall: string;
  decision: Decision;
  files: { path: string; summary: string }[];
  /** True when the text is still arriving and the last section may be cut. */
  partial?: boolean;
}

const DECISIONS: readonly Decision[] = ["approve", "comment", "request_changes"];

export function parseSummaryText(text: string, partial = false): Summary {
  const lines = text.replace(/\r\n?/g, "\n").split("\n");
  let decision: Decision = "comment";
  let overall: string[] = [];
  const files: { path: string; summary: string }[] = [];
  let current: string[] | null = null;
  let currentPath: string | null = null;
  const flush = () => {
    if (currentPath !== null && current) files.push({ path: currentPath, summary: current.join("\n").trim() });
    current = null;
    currentPath = null;
  };
  for (const raw of lines) {
    const line = raw.trimEnd();
    const decisionMatch = /^\s*\**decision\**\s*[:：]\s*\**\s*([a-z_ ]+)/i.exec(line);
    if (decisionMatch && currentPath === null && overall.length === 0) {
      const d = decisionMatch[1].trim().toLowerCase().replace(/\s+/g, "_") as Decision;
      if (DECISIONS.includes(d)) decision = d;
      continue;
    }
    // A bare "##" is a heading still arriving: hold it out of the text.
    if (/^\s*#{1,6}\s*$/.test(line)) continue;
    const heading = /^\s*#{1,6}\s+(.+?)\s*$/.exec(line);
    if (heading) {
      flush();
      // Models decorate headings: `path`, **path**, _path_.
      const title = heading[1].replace(/^[`*_\s]+|[`*_\s]+$/g, "").trim();
      if (/^overall$/i.test(title)) {
        currentPath = null;
        current = overall; // a second Overall continues the first
        continue;
      }
      currentPath = title;
      current = [];
      continue;
    }
    if (current) current.push(line);
  }
  flush();
  return { overall: overall.join("\n").trim(), decision, files, ...(partial ? { partial: true } : {}) };
}

/** The reviewer's text, or a structured result from an older deployment, as a Summary. */
export function readSummaryResult(result: unknown): Summary | null {
  if (typeof result === "string") return parseSummaryText(result);
  if (result && typeof result === "object" && "overall" in result && "files" in result) {
    const r = result as { overall?: unknown; decision?: unknown; files?: unknown };
    if (typeof r.overall !== "string" || !Array.isArray(r.files)) return null;
    const decision = DECISIONS.includes(r.decision as Decision) ? (r.decision as Decision) : "comment";
    return {
      overall: r.overall,
      decision,
      files: r.files
        .filter((f): f is { path: string; summary: string } => !!f && typeof f === "object" && typeof (f as { path?: unknown }).path === "string" && typeof (f as { summary?: unknown }).summary === "string")
        .map((f) => ({ path: f.path, summary: f.summary })),
    };
  }
  return null;
}
