/**
 * What the reviewer subagent (Luna) writes, and how it is read back.
 *
 * The reviewer writes plain text in a fixed layout rather than structured
 * output, so that the page can stream it in as it is generated:
 *
 *   Decision: request_changes
 *   ## Overall
 *   <three to five sentences>
 *   ## src/path/one.ts
 *   <two to three sentences>
 *   ## src/path/two.ts
 *   …
 *
 * `parseSummaryText` is tolerant of partial text, so it can run on every
 * streamed delta as well as on the final result.
 */

/** Files per reviewer task. A review is split into parallel tasks of this many files, plus one overall task. */
export const REVIEW_BATCH_SIZE = 6;

/** What one reviewer task was asked for. */
type ReviewPartRole = 'files' | 'overall';

export interface ReviewPart {
  role: ReviewPartRole;
  /** Batch index for "files" parts; 0 for the overall part. */
  index: number;
  /** The paths this part covers (every path for the overall part). */
  paths: string[];
}

/** The model behind the reviewer, shown as "Generated by …". */
export const REVIEWER_MODEL = 'openai/gpt-5.6-luna-fast';

type Decision = 'approve' | 'comment' | 'request_changes';

export interface Summary {
  overall: string;
  decision: Decision;
  files: { path: string; summary: string }[];
  /** True when the text is still arriving and the last section may be cut. */
  partial?: boolean;
}

const DECISIONS: readonly Decision[] = [
  'approve',
  'comment',
  'request_changes',
];

/** The review as it is being read, line by line. */
interface SummaryParse {
  /** The section being read into, which is `overall` while that is the one. */
  current: string[] | null;
  /** The path that section is about, or null while the overall one is open. */
  currentPath: string | null;
  decision: Decision;
  files: { path: string; summary: string }[];
  overall: string[];
}

/**
 * A `Decision:` line: the decision it names, 'unrecognised' when the line is
 * one but the word is not a decision, and null when it is not one at all.
 */
function readDecisionLine(line: string): Decision | 'unrecognised' | null {
  const match = /^\s*\**decision\**\s*[:：]\s*\**\s*([a-z_ ]+)/i.exec(line);
  if (!match) {
    return null;
  }
  const named = match[1].trim().toLowerCase().replace(/\s+/g, '_') as Decision;
  return DECISIONS.includes(named) ? named : 'unrecognised';
}

/** A heading's title, stripped of the decoration models put around paths. */
function readHeading(line: string): string | null {
  const heading = /^\s*#{1,6}\s+(.+?)\s*$/.exec(line);
  // Models decorate headings: `path`, **path**, _path_.
  return heading ? heading[1].replace(/^[`*_\s]+|[`*_\s]+$/g, '').trim() : null;
}

/** Close the section being read, if one is open. */
function flushSection(parse: SummaryParse): void {
  if (parse.currentPath !== null && parse.current) {
    parse.files.push({
      path: parse.currentPath,
      summary: parse.current.join('\n').trim(),
    });
  }
  parse.current = null;
  parse.currentPath = null;
}

/** Open the section a heading names. A second `Overall` continues the first. */
function openSection(parse: SummaryParse, title: string): void {
  flushSection(parse);
  if (/^overall$/i.test(title)) {
    parse.currentPath = null;
    parse.current = parse.overall;
    return;
  }
  parse.currentPath = title;
  parse.current = [];
}

/** Read one line of the reviewer's text into the parse. */
function readSummaryLine(parse: SummaryParse, raw: string): void {
  const line = raw.trimEnd();
  const named = readDecisionLine(line);
  if (named && parse.currentPath === null && parse.overall.length === 0) {
    if (named !== 'unrecognised') {
      parse.decision = named;
    }
    return;
  }
  // A bare "##" is a heading still arriving: hold it out of the text.
  if (/^\s*#{1,6}\s*$/.test(line)) {
    return;
  }
  const title = readHeading(line);
  if (title !== null) {
    openSection(parse, title);
    return;
  }
  parse.current?.push(line);
}

export function parseSummaryText(text: string, partial = false): Summary {
  const parse: SummaryParse = {
    current: null,
    currentPath: null,
    decision: 'comment',
    files: [],
    overall: [],
  };
  for (const raw of text.replace(/\r\n?/g, '\n').split('\n')) {
    readSummaryLine(parse, raw);
  }
  flushSection(parse);
  return {
    decision: parse.decision,
    files: parse.files,
    overall: parse.overall.join('\n').trim(),
    ...(partial ? { partial: true } : {}),
  };
}
