import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import type { ReactNode } from 'react';

import { SITE } from '@/lib/site';
import { THEME_SCRIPT } from '@/lib/theme';
import './globals.css';

const sans = Geist({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-sans',
  weight: 'variable',
});

const mono = Geist_Mono({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-mono',
  weight: 'variable',
});

/**
 * What this page tells a crawler, a link preview and an answer engine.
 *
 * `metadataBase` is what makes every relative URL below absolute, including
 * the Open Graph image generated by `opengraph-image.tsx`. The title carries a
 * template so that a second route — a permalinked review, say — reads as part
 * of the same product without repeating its name.
 */
export const metadata: Metadata = {
  alternates: { canonical: '/' },
  applicationName: SITE.name,
  authors: [{ name: 'frostney', url: 'https://github.com/frostney' }],
  category: 'developer tools',
  creator: 'frostney',
  description: SITE.description,
  keywords: [
    'clean code',
    'code review',
    'pull request review',
    'AI code review',
    'code smells',
    'Clean Code checklist',
    'GitHub pull request',
    'diff review',
    'Jev',
    'TypeSafe',
    'eve agent',
  ],
  metadataBase: new URL(SITE.url),
  openGraph: {
    description: SITE.description,
    locale: 'en_US',
    siteName: SITE.name,
    title: SITE.name,
    type: 'website',
    url: SITE.url,
  },
  robots: { follow: true, index: true },
  title: {
    default: SITE.name,
    template: `%s · ${SITE.name}`,
  },
  twitter: {
    card: 'summary_large_image',
    description: SITE.description,
    title: SITE.name,
  },
};

export default function RootLayout({
  children,
}: {
  readonly children: ReactNode;
}) {
  return (
    <html
      className={`${sans.variable} ${mono.variable}`}
      lang="en"
      suppressHydrationWarning={true}
    >
      <body className="font-sans antialiased">
        {/* The theme, before the first pixel. It is the first thing in the
            document body so that the attribute the palette keys off is already
            on `<html>` when the browser paints, rather than one render later —
            a page that flashes white on the way to black has told the reader it
            forgot which one they asked for. */}
        <script
          // biome-ignore lint/security/noDangerouslySetInnerHtml: an inline script is the only thing that runs before paint, and every byte of it is written in lib/theme.ts
          dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }}
        />
        {children}
      </body>
    </html>
  );
}
