import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { ReactNode } from "react";
import { SITE } from "@/lib/site";
import { THEME_SCRIPT } from "@/lib/theme";
import "./globals.css";

const sans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: "variable",
  display: "swap",
});

const mono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: "variable",
  display: "swap",
});

/**
 * What this page tells a crawler, a link preview and an answer engine.
 *
 * `metadataBase` is what makes every relative URL below absolute, including
 * the Open Graph image generated by `opengraph-image.tsx`. The title carries a
 * template so that a second route — a permalinked review, say — reads as part
 * of the same product without repeating its name.
 */
export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: SITE.name,
    template: `%s · ${SITE.name}`,
  },
  description: SITE.description,
  applicationName: SITE.name,
  category: "developer tools",
  keywords: [
    "clean code",
    "code review",
    "pull request review",
    "AI code review",
    "code smells",
    "Clean Code checklist",
    "GitHub pull request",
    "diff review",
    "Jev",
    "TypeSafe",
    "eve agent",
  ],
  authors: [{ name: "frostney", url: "https://github.com/frostney" }],
  creator: "frostney",
  alternates: { canonical: "/" },
  robots: { index: true, follow: true },
  openGraph: {
    type: "website",
    siteName: SITE.name,
    url: SITE.url,
    locale: "en_US",
    title: SITE.name,
    description: SITE.description,
  },
  twitter: {
    card: "summary_large_image",
    title: SITE.name,
    description: SITE.description,
  },
};

export default function RootLayout({ children }: { readonly children: ReactNode }) {
  return (
    <html className={`${sans.variable} ${mono.variable}`} lang="en" suppressHydrationWarning>
      <body className="font-sans antialiased">
        {/* The theme, before the first pixel. It is the first thing in the
            document body so that the attribute the palette keys off is already
            on `<html>` when the browser paints, rather than one render later —
            a page that flashes white on the way to black has told the reader it
            forgot which one they asked for. */}
        <script
          // biome-ignore lint/security/noDangerouslySetInnerHtml: an inline script is the only thing that runs before paint, and every byte of it is written in lib/theme.ts
          dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }}
        />
        {children}
      </body>
    </html>
  );
}
