import type { ReactNode } from "react";
import { DECISIONS, type Decision, REVIEWER_MODEL, type SummaryStatus } from "@/lib/display";

/**
 * Luna's prose, styled as the one thing on this page that is not a meter: a
 * review comment. Who wrote it, what they concluded, what they said, and which
 * model said it.
 *
 * The same block does the whole change and one file, so the two read as the
 * same voice at two altitudes. What it concluded and who wrote it share the
 * bottom line: the decision on the left, then — for the review of the whole
 * change — Jev's own verdict, the smell count and what is running, with the
 * model on the right and the prose above them. Five states, all of them on
 * `data-summary`:
 * nothing written yet (a spinner where the text will be), the text arriving
 * word by word from the reviewer's own stream, the previous text held at half
 * opacity while a fresh one is written, the settled text, and the quiet
 * admission that there is none.
 *
 * The review is written from the judge's findings — the reviewer never sees the
 * code — so it names smells rather than lines, and its `code` spans are the
 * words it borrowed from the finding, not quotes from the file.
 */
export function ReviewNote({
  status,
  text,
  decision,
  error,
  model,
  pills,
  writing = false,
  tone = "file",
}: {
  status: SummaryStatus;
  text: string | null | undefined;
  /** Only the review of the whole change carries one. */
  decision?: Decision | null;
  /** The review's own pills, immediately right of the decision badge. */
  pills?: ReactNode;
  /** Why the review never arrived, when the agent said. */
  error?: string | null;
  /** The model that wrote it, as the payload named it. */
  model?: string | null;
  /** This is the block being written right now: the caret belongs at its end. */
  writing?: boolean;
  tone?: "overall" | "file";
}) {
  const badge = decision ? DECISIONS[decision] : null;
  return (
    <section
      data-summary={status}
      className={`rounded-md border border-line ${tone === "overall" ? "bg-surface" : "bg-white"} px-3 py-2`}
    >
      {status === "stale" && (
        <div className="mb-1 flex">
          <span className="ml-auto flex shrink-0 items-center gap-1.5 text-[11px] text-muted">
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-warn" />
            reviewing…
          </span>
        </div>
      )}
      <Body status={status} text={text} error={error} tone={tone} writing={writing} />
      <div className="mt-1.5 flex flex-wrap items-center gap-x-2 gap-y-1">
        {badge && (
          <span
            data-decision={decision}
            className={`rounded-full px-2 py-0.5 text-[11px] font-semibold ${badge.className}`}
          >
            {badge.label}
          </span>
        )}
        {pills}
        <p data-generated-by className="ml-auto text-right text-[11px] text-muted/80">
          Generated by {model?.trim() || REVIEWER_MODEL}
        </p>
      </div>
    </section>
  );
}

/** As much of a failure as belongs on one quiet line. */
const ERROR_CHARS = 120;

function Body({
  status,
  text,
  error,
  tone,
  writing,
}: {
  status: SummaryStatus;
  text: string | null | undefined;
  error?: string | null;
  tone: "overall" | "file";
  writing: boolean;
}) {
  if (status === "pending" || (!text && status !== "failed")) {
    return (
      <p className="flex items-center gap-2 text-[13px] text-muted">
        <span className="spinner" aria-hidden="true" />
        Luna is reviewing…
      </p>
    );
  }
  // Still quiet — a review that did not arrive is not an error banner — but
  // with the reason on it when there is one.
  if (!text) {
    const why = error?.trim().slice(0, ERROR_CHARS);
    return <p className="text-[13px] text-muted">{why ? `No review: ${why}` : "No review yet"}</p>;
  }
  return (
    <p
      className={`text-[13px] leading-relaxed text-ink ${tone === "overall" ? "" : "text-[12.5px]"}`}
      style={status === "stale" ? { opacity: 0.5 } : undefined}
    >
      {ticked(text)}
      {writing && <span className="caret" aria-hidden="true" />}
    </p>
  );
}

/**
 * `` `code` `` spans as code. The reviewer is asked for backticks around
 * identifiers and paths, and this is the whole of the markdown the page reads:
 * the text is split on the ticks and rendered as React nodes, so nothing the
 * model writes can become markup.
 */
function ticked(text: string): ReactNode[] {
  return text.split(/(`[^`\n]+`)/g).map((part, i) =>
    part.length > 2 && part.startsWith("`") && part.endsWith("`") ? (
      <code
        // biome-ignore lint/suspicious/noArrayIndexKey: a span's identity is its position in the text
        key={i}
        className="rounded bg-track px-1 py-px font-mono text-[0.9em] text-ink"
      >
        {part.slice(1, -1)}
      </code>
    ) : (
      part
    ),
  );
}
