import type { ReactNode } from 'react';

import { REVIEWER_MODEL } from '@/agent/lib/summary';
import { DECISIONS, type Decision, type SummaryStatus } from '@/lib/display';

/**
 * Luna's prose, styled as the one thing on this page that is not a meter: a
 * review comment. Who wrote it, what they concluded, what they said, and which
 * model said it.
 *
 * The same block does the whole change and one file, so the two read as the
 * same voice at two altitudes. What it concluded and who wrote it share the
 * bottom line: the decision on the left, then — for the review of the whole
 * change — Jev's own verdict, the smell count and what is running, with the
 * model on the right and the prose above them. Five states, all of them on
 * `data-summary`:
 * nothing written yet (a spinner where the text will be), the text arriving
 * word by word from the reviewer's own stream, the previous text held at half
 * opacity while a fresh one is written, the settled text, and the quiet
 * admission that there is none.
 *
 * The review is written from the judge's findings — the reviewer never sees the
 * code — so it names smells rather than lines, and its `code` spans are the
 * words it borrowed from the finding, not quotes from the file.
 */
export function ReviewNote({
  status,
  text,
  decision,
  error,
  model,
  pills,
  incomplete = false,
  writing = false,
  tone = 'file',
}: {
  status: SummaryStatus;
  text: string | null | undefined;
  /** Only the review of the whole change carries one. */
  decision?: Decision | null;
  /** The review's own pills, immediately right of the decision badge. */
  pills?: ReactNode;
  /** Why the review never arrived, when the agent said. */
  error?: string | null;
  /** The model that wrote it, as the payload named it. */
  model?: string | null;
  /** Luna was cut off in this block at its length limit: the text is as far as it got. */
  incomplete?: boolean;
  /** This is the block being written right now: the caret belongs at its end. */
  writing?: boolean;
  tone?: 'overall' | 'file';
}) {
  const badge = decision ? DECISIONS[decision] : null;
  return (
    <section
      className={`rounded-md border border-line ${tone === 'overall' ? 'bg-surface' : 'bg-page'} px-3 py-2`}
      data-summary={status}
    >
      {status === 'stale' && (
        <div className="mb-1 flex">
          <span className="ml-auto flex shrink-0 items-center gap-1.5 text-tiny text-muted">
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-warn" />
            reviewing…
          </span>
        </div>
      )}
      <Body
        error={error}
        incomplete={incomplete}
        status={status}
        text={text}
        tone={tone}
        writing={writing}
      />
      <div className="mt-1.5 flex flex-wrap items-center gap-x-2 gap-y-1">
        {badge ? (
          <span
            className={`rounded-full px-2 py-0.5 text-tiny font-semibold ${badge.className}`}
            data-decision={decision}
          >
            {badge.label}
          </span>
        ) : null}
        {pills}
        {/* Four pills and an attribution do not share one phone-width line, so
            below the two-column breakpoint the attribution takes a line of its
            own under them rather than wrapping to a lonely right margin. */}
        <p
          className="w-full text-tiny text-muted/80 lg:ml-auto lg:w-auto lg:text-right"
          data-generated-by={true}
        >
          Generated by {model?.trim() || REVIEWER_MODEL}
        </p>
      </div>
    </section>
  );
}

/** As much of a failure as belongs on one quiet line. */
const ERROR_CHARS = 120;

function Body({
  status,
  text,
  error,
  incomplete,
  tone,
  writing,
}: {
  status: SummaryStatus;
  text: string | null | undefined;
  error?: string | null;
  incomplete: boolean;
  tone: 'overall' | 'file';
  writing: boolean;
}) {
  if (status === 'pending' || (!text && status !== 'failed')) {
    return (
      <p className="flex items-center gap-2 text-[14px] text-muted lg:text-[13px]">
        <span aria-hidden="true" className="spinner" />
        Luna is reviewing…
      </p>
    );
  }
  // Still quiet — a review that did not arrive is not an error banner — but
  // with the reason on it when there is one.
  if (!text && incomplete) {
    return (
      <p
        className="text-[14px] text-muted lg:text-[13px]"
        data-incomplete="true"
      >
        No review: Luna ran into its length limit before it reached this.
      </p>
    );
  }
  if (!text) {
    const why = error?.trim().slice(0, ERROR_CHARS);
    return (
      <p className="text-[14px] text-muted lg:text-[13px]">
        {why ? `No review: ${why}` : 'No review yet'}
      </p>
    );
  }
  return (
    <>
      <p
        className={`leading-relaxed text-ink ${tone === 'overall' ? 'text-[14px] lg:text-[13px]' : 'text-[13px] lg:text-[12.5px]'}`}
        style={status === 'stale' ? { opacity: 0.5 } : undefined}
      >
        {ticked(text)}
        {writing ? <span aria-hidden="true" className="caret" /> : null}
      </p>
      {incomplete && !writing ? (
        <p className="mt-1 text-tiny text-muted" data-incomplete="true">
          Cut off: Luna ran into its length limit, so this is as far as it got.
        </p>
      ) : null}
    </>
  );
}

/**
 * `` `code` `` spans as code. The reviewer is asked for backticks around
 * identifiers and paths, and this is the whole of the markdown the page reads:
 * the text is split on the ticks and rendered as React nodes, so nothing the
 * model writes can become markup.
 */
function ticked(text: string): ReactNode[] {
  return text.split(/(`[^`\n]+`)/g).map((part, i) =>
    part.length > 2 && part.startsWith('`') && part.endsWith('`') ? (
      <code
        className="rounded bg-track px-1 py-px font-mono text-[12px] text-ink lg:text-[0.9em]"
        // A span's identity is where it sits in the text and what it says: the
        // position alone would keep a stale node while the review streams in.
        key={`${i}:${part}`}
      >
        {part.slice(1, -1)}
      </code>
    ) : (
      part
    ),
  );
}
